# Generated by Django 3.2.18 on 2023-03-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('strategy', models.CharField(max_length=200)),
                ('aum', models.IntegerField(blank=True, verbose_name='AUM (USD)')),
                ('inception_date', models.DateTimeField(blank=True, verbose_name='Inception Date')),
            ],
        ),
    ]
