# Generated by Django 3.2.18 on 2023-03-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundsapp', '0002_auto_20230302_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='aum',
            field=models.IntegerField(blank=True, null=True, verbose_name='AUM (USD)'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='inception_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inception Date'),
        ),
    ]
